version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mentorship_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mentorship_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mentorship_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/mentorship_db
    volumes:
      - .:/app
    command: ["python", "src/main.py"]

volumes:
  postgres_data:
